Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 130

Metrics/LineLength:
  Max: 280
  IgnoredPatterns: ['\A#']

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 10

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'config/routes.rb'
